# official tutorial 
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/

site_name: 许俊毅XJY的个人网站
site_author: 许俊毅

repo_name: self-learning-UG
repo_url: https://github.com/xujunyi88/self-learning-UG
copyright: Copyright &copy; 2021-present <a href="https://github.com/xujunyi88" target="_blank" rel="noopener noreferrer">许俊毅XJY</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  apple-touch-icon-precomposed: images/mobile_icon.png
  include_search_page: false
  search_index_only: true

features:
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.annotate
    - tabs

palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: light blue
    accent: deep purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: cyan
    accent: deep purple
    toggle:
      icon: material/weather-night
      name: Switch to light mode

font:
  text: Roboto
  code: Roboto Mono

icon:
  repo: fontawesome/brands/github

markdown_extensions: 
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/
  - pymdownx.tabbed  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - nl2br # newline-to-break
  - md_in_html
  - footnotes

plugins:
  - search
  - roamlinks
    #- autolinks 
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xujunyi88
  analytics:
    provider: google
    property: G-KJB4RXSKZG

nav:
  - 前言: 'index.md'
  - 信息科学技术学院:
      - 电子信息科学技术专业:
          - 电科-课程信息: '1-信息科学技术学院/1-电子信息科学与技术专业/1-电科-课程信息.md'
          - 电科-培养路线: '1-信息科学技术学院/1-电子信息科学与技术专业/2-电科-培养路线.md'
          - 电科-培养方案: '1-信息科学技术学院/1-电子信息科学与技术专业/3-电科-培养方案.md'


